---
- name: refresh docker repos
  apt: update_cache=yes
  sudo: False
  tags:
    - setup
    - docker

- name: restart docker service
  systemd: name=docker state=restarted enabled=yes daemon-reload=yes
  sudo: False
