---
- name: Add Docker repository key
  shell: "apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D"
  sudo: False
  tags:
    - setup
    - docker

- name: Add Docker repository
  apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release }} main' state=present
  sudo: False
  tags:
    - setup
    - docker
  notify: refresh docker repos

- name: Install Docker packages and related python-docker for Ansible management
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - docker-engine
    - python-docker
  sudo: False
  notify: restart docker service
  tags:
    - setup
    - docker

- name: allow all incoming traffic on docker0 interface from docker vms
  ufw: interface=docker0 direction=in rule=allow src=172.17.0.1/16
  tags:
    - setup
    - docker

