---
- name: install ufw first
  apt: name=ufw state=present
  sudo: True
  tags:
    - setup
    - ufw

- name: setup ufw logging
  ufw: logging=on
  sudo: True
  tags:
    - setup
    - ufw

- name: deny incoming traffic
  ufw: direction=incoming policy=deny
  sudo: True
  tags:
    - setup
    - ufw

- name: allow forward traffic
  ufw: direction=routed policy=allow
  sudo: True
  tags:
    - setup
    - ufw

- name: allow incoming ssh
  ufw: rule=allow direction=in port=ssh proto=tcp
  sudo: True
  tags:
    - ufw

- name: allow incoming http
  ufw: rule=allow direction=in port=http proto=tcp
  sudo: True
  tags:
    - ufw

- name: allow incoming 2222
  ufw: rule=allow direction=in port=2222 proto=tcp
  sudo: True
  tags:
    - ufw

- name: at the end of configuring, enable and reload ufw
  ufw: state=enabled
  sudo: True
  tags:
    - setup
    - ufw
