- name: install set of standard tools - git, text editors, htop...
  apt: name={{ item }} state=present update_cache=yes
  with_items:
   - htop
   - vim-nox
   - wget
   - curl
   - iotop
   - telnet
   - rsync
   - python-apt
   - fail2ban
   - apt-transport-https
   - ca-certificates
   - tmux
  sudo: False
  notify: restart common services
  tags:
    - setup

- name: prepare u3 data dir for docker volumes
  file: state=directory path=/srv/data/u3data recurse=yes
  tags:
    - setup

- name: prepare u3 data temp dir for docker volumes
  file: state=directory path=/srv/data/u3data/tmp recurse=yes
  tags:
    - setup
