---
- name: check permissions set to scrapers containers volume path
  file: path='{{u3_host_volume}}' state=directory owner='{{u3_host_volume_user}}' group='{{u3_host_volume_group}}' mode=0644

- name: pull scraper image before any container work
  docker_image:
    name: '{{scraper_image}}'
    force: yes

- name: pull datadog image before any container work
  docker_image:
    name: '{{dd_image}}'
    force: yes

- name: Before any scrapers are setup, we need to setup Datadog stats container
  docker_container:
    name: '{{dd_container_name}}'
    image: '{{dd_image}}'
    state: '{{dd_state}}'
    command: '{{dd_command}}'
    log_driver: '{{dd_log_driver}}'
    volumes:
      - '{{dd_docker_socket_volume}}'
    env:
      API_KEY: '{{dd_env_api_key}}'
      LOG_LEVEL: '{{dd_env_log_level}}'
      DD_LOG_LEVEL: '{{dd_env_log_level}}'

- name: manage rul scraper
  docker_container:
    name: '{{rul_name}}'
    image: '{{scraper_image}}'
    state: '{{rul_state}}'
    command: '{{rul_command}}'
    volumes: 
      - '{{scraper_volume}}'
    log_driver: '{{scraper_log_driver}}'
    env:
      DATABASE_URL: '{{scraper_db_url}}'
      FILES_STORE: './data/files/{{ rul_name }}'
      SENTRY_DSN: '{{scraper_sentry_dsn}}' # Sentry DSN if available 
    links:
      - '{{dd_container_name}}'

- name: manage bf scraper
  docker_container:
    name: '{{bf_name}}'
    image: '{{scraper_image}}'
    state:  '{{bf_state}}'
    command: '{{bf_command}}'
    volumes:
      - '{{scraper_volume}}'
    log_driver: '{{scraper_log_driver}}'
    env:
      DATABASE_URL: '{{scraper_db_url}}'
      FILES_STORE: './data/files/{{ bf_name }}'
      SENTRY_DSN: '{{scraper_sentry_dsn}}' # Sentry DSN if available 
    links:
      - '{{dd_container_name}}'

- name: manage dkum scraper
  docker_container:
    name: '{{dkum_name}}'
    image: '{{scraper_image}}'
    state:  '{{dkum_state}}'
    command: '{{dkum_command}}'
    volumes:
      - '{{scraper_volume}}'
    log_driver: '{{scraper_log_driver}}'
    env:
      DATABASE_URL: '{{scraper_db_url}}'
      FILES_STORE: './data/files/{{ dkum_name }}'
      SENTRY_DSN: '{{scraper_sentry_dsn}}' # Sentry DSN if available 
    links:
      - '{{dd_container_name}}'

- name: manage fammit scraper
  docker_container:
    name: '{{fammit_name}}'
    image: '{{scraper_image}}'
    state:  '{{fammit_state}}'
    command: '{{fammit_command}}'
    volumes:
      - '{{scraper_volume}}'
    log_driver: '{{scraper_log_driver}}'
    env:
      DATABASE_URL: '{{scraper_db_url}}'
      FILES_STORE: './data/files/{{ fammit_name }}'
      SENTRY_DSN: '{{scraper_sentry_dsn}}' # Sentry DSN if available 
    links:
      - '{{dd_container_name}}'

- name: manage ung scraper
  docker_container:
    name: '{{ung_name}}'
    image: '{{scraper_image}}'
    state:  '{{ung_state}}'
    command: '{{ung_command}}'
    volumes:
      - '{{scraper_volume}}'
    log_driver: '{{scraper_log_driver}}'
    env:
      DATABASE_URL: '{{scraper_db_url}}'
      FILES_STORE: './data/files/{{ ung_name }}'
      SENTRY_DSN: '{{scraper_sentry_dsn}}' # Sentry DSN if available 
    links:
      - '{{dd_container_name}}'
